#pragma once

#include <QIODevice>
#include <array>
#include <vector>
#include <atomic>
#include <cmath>
#include <memory>
#include "Buffer.h"
#include "Constants.h"
#include "AudioRecorder.h"
#include "HarmonicControlPanel.h"
#include "SpectrumAnalyzer.h"
#include "WaveForm.h"

/**
* CAudioConsumer: Consumers the generated Audio in the Buffer generated by the AudioGenerator Class
 */

class CAudioConsumer : public QIODevice 
{
    Q_OBJECT

public:

    explicit CAudioConsumer(QObject* parent = nullptr);
    
    // Start audio generation
    void start();
    qint64 bytesAvailable() const override;
    
    // Set the audio output buffer (int16_t for QAudioSink)
    void setAudioOutputBuffer(CBuffer<int16_t>& audioOutputBuffer) { m_audioOutputBuffer = &audioOutputBuffer; }
    
    // Set the mixed buffer (double for visualization)
    void setMixedBuffer(CBuffer<double>& mixedBuffer) { m_mixedBuffer = &mixedBuffer; }

    // Set the harmonic buffers array (0-7 for 8 harmonics)
    void setHarmonicBuffers(std::array<CBuffer<double>, AudioConstants::NUM_HARMONICS>& harmonicBuffers) { m_harmonicBuffers = &harmonicBuffers; }
    
    // Start recording audio to a WAV file with auto generated filename
    bool startRecording();

    // Stop the current recording
    void stopRecording();

    // Check if it is already currently recording
    bool isRecording() const;
    
    // Get the path of the last recorded file
    QString getLastRecordingPath() const;

    void setWaveform(CWaveform& waveform){m_waveform = &waveform;};
    void setSpectrumAnalyzer(CSpectrumAnalyzer& spectrumAnalyzer){m_spectrumAnalyzer = &spectrumAnalyzer;};
    void setHarmonicControlPanel(CHarmonicControlPanel& harmonicControlPanel){m_harmonicPanel = &harmonicControlPanel;};


protected:
    qint64 readData(char* data, qint64 maxlen) override;
    qint64 writeData(const char* data, qint64 len) override;

private:
    const int m_sampleRate{AudioConstants::SAMPLE_RATE};
    const int m_numHarmonics{AudioConstants::NUM_HARMONICS};
    
    double m_currentPhase{0.0};
    double m_lastSample = 0.0;

    std::atomic<double> m_fundamental{220.0};
    std::atomic<double> m_masterAmplitude{0.7};
    std::atomic<double> m_distortion{0.0};
    std::atomic<double> m_filter{1.0};
    std::atomic<double> m_reverbMix{0.0};

    size_t m_activeHarmonicCount{0};
    
    CBuffer<int16_t>* m_audioOutputBuffer;  // int16_t output from generator
    CBuffer<double>* m_mixedBuffer;          // double mixed signal for visualization
    std::array<CBuffer<double>, AudioConstants::NUM_HARMONICS>* m_harmonicBuffers;  // Individual harmonics (0-7)    

    
    CWaveform* m_waveform;
    CAudioRecorder m_recorder;

    CSpectrumAnalyzer* m_spectrumAnalyzer;
    CHarmonicControlPanel* m_harmonicPanel;

signals:
    void generateAudio();
    void requestGuiUpdate();

};

